# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SignName' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 pod 'SDWebImage'
end
